// flow-typed signature: 28298e5c3454d7b2686b8542817c62d5
// flow-typed version: <<STUB>>/mssql_v^3.3.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mssql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mssql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mssql/lib/cli' {
  declare module.exports: any;
}

declare module 'mssql/lib/connectionstring' {
  declare module.exports: any;
}

declare module 'mssql/lib/datatypes' {
  declare module.exports: any;
}

declare module 'mssql/lib/isolationlevel' {
  declare module.exports: any;
}

declare module 'mssql/lib/main' {
  declare module.exports: any;
}

declare module 'mssql/lib/msnodesql' {
  declare module.exports: any;
}

declare module 'mssql/lib/msnodesqlv8' {
  declare module.exports: any;
}

declare module 'mssql/lib/table' {
  declare module.exports: any;
}

declare module 'mssql/lib/tds-fix' {
  declare module.exports: any;
}

declare module 'mssql/lib/tds' {
  declare module.exports: any;
}

declare module 'mssql/lib/tedious' {
  declare module.exports: any;
}

declare module 'mssql/lib/udt' {
  declare module.exports: any;
}

declare module 'mssql/nofix' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mssql/index' {
  declare module.exports: $Exports<'mssql'>;
}
declare module 'mssql/index.js' {
  declare module.exports: $Exports<'mssql'>;
}
declare module 'mssql/lib/cli.js' {
  declare module.exports: $Exports<'mssql/lib/cli'>;
}
declare module 'mssql/lib/connectionstring.js' {
  declare module.exports: $Exports<'mssql/lib/connectionstring'>;
}
declare module 'mssql/lib/datatypes.js' {
  declare module.exports: $Exports<'mssql/lib/datatypes'>;
}
declare module 'mssql/lib/isolationlevel.js' {
  declare module.exports: $Exports<'mssql/lib/isolationlevel'>;
}
declare module 'mssql/lib/main.js' {
  declare module.exports: $Exports<'mssql/lib/main'>;
}
declare module 'mssql/lib/msnodesql.js' {
  declare module.exports: $Exports<'mssql/lib/msnodesql'>;
}
declare module 'mssql/lib/msnodesqlv8.js' {
  declare module.exports: $Exports<'mssql/lib/msnodesqlv8'>;
}
declare module 'mssql/lib/table.js' {
  declare module.exports: $Exports<'mssql/lib/table'>;
}
declare module 'mssql/lib/tds-fix.js' {
  declare module.exports: $Exports<'mssql/lib/tds-fix'>;
}
declare module 'mssql/lib/tds.js' {
  declare module.exports: $Exports<'mssql/lib/tds'>;
}
declare module 'mssql/lib/tedious.js' {
  declare module.exports: $Exports<'mssql/lib/tedious'>;
}
declare module 'mssql/lib/udt.js' {
  declare module.exports: $Exports<'mssql/lib/udt'>;
}
declare module 'mssql/nofix.js' {
  declare module.exports: $Exports<'mssql/nofix'>;
}
